server.port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://freedb.tech/freedbtech_remindermeetings
    username: freedbtech_vargoadventure
    password: hibatullah22
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  messages.basename: i18n/messages

